### ISSUE TITLE
Per-user group creation error

### ISSUE THREAD

**Issue by Stonemage** [singleplatform-eng/ansible-users#43]
I am getting the following error after upgrading ansible to 2.2.0.0

`fatal: [xcp05.xxx.xxx.net]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'uid'\n\nThe error appears to have been in '/etc/ansible/roles/mivok0.users/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Per-user group creation\n  ^ here\n"}`

I cannot for the life of me work out what's going on here... any ideas?

**Comment by ghost** [comment]
Are you sure all of the items in your `users` list have the required `uid` attribute?

**Comment by ghost** [comment]
Closing this for now. Feel free to post more information here if you continue to experience issues.
